name: PetControl
version: '${version}'
main: org.infotoast.petcontrol.PetControl
api-version: '1.21'
description: Manages pets, transfers ownership, and tames wild animals
load: STARTUP
author: Frank
website: infotoast.org
commands:
  petinfo:
    description: Gets info on a tamable animal
    permission: petcontrol.petinfo
    usage: "Usage: /<command>"
  transferpetowner:
    description: Transfers ownership of a pet
    permission: petcontrol.transferpetowner
    usage: "Usage: /<command> <owner>"
  tamepet:
    description: Tames an unowned tamable mob
    permission: petcontrol.tamepet
    usage: "/<command> [owner]"
  togglesit:
    description: Toggles whether an animal is sitting, regardless of owner
    permission: petcontrol.togglesit
    usage: "/<command>"
  healpet:
    description: Heals the tamable animal you're looking at
    permission: petcontrol.heal
    usage: "/<command>"
  roam:
    description: Makes the pet roam around instead of following you
    permission: petcontrol.roam
    usage: "/<command> <radius> [center x] [center z] [guarded]"
  follow:
    description: Makes a roaming animal go back to follow (normal) mode
    permission: petcontrol.follow
    usage: "/<command>"

permissions:
  petcontrol.petinfo:
    description: Allows you to use /petinfo
    default: true
  petcontrol.transferpetowner:
    description: Allows you to transfer pet ownership with /transferpetowner
    default: op
  petcontrol.tamepet.self:
    description: Allows you to tame pet to be owned by yourself
    default: op
  petcontrol.tamepet.others:
    description: Allows you to tame pets to be given to others
    default: op
  petcontrol.togglesit:
    description: Allows you to toggle pet sitting with /togglesit
    default: op
  petcontrol.heal:
    description: Allows you to heal pets with /healpet
    default: op
  petcontrol.roam:
    description: Makes pets roam around instead of following you
    default: true
  petcontrol.roam.others:
    description: Allows you to roam other's pets
    default: op
  petcontrol.roam.guarded:
    description: Allows you to set guarded mode when pets are roaming
    default: op
  petcontrol.follow:
    description: Allows you to use /follow
    default: true
  petcontrol.follow.others:
    description: Allows you to set other's animals to follow mode
    default: op
